# Auto-generated providers from discovery
# Generated by ProviderDiscovery Tool
# 
# Add these to your providers.py file

from sms_bomber.api.providers import Provider

discovered_providers = [
    Provider(
        name="Taaghche OTP",
        url="https://taaghche.com/v4/site/auth/login-with-otp",
        data_template={"phone": "{phone}"},
    ),
    Provider(
        name="Taaghche OTP",
        url="https://taaghche.com/v4/site/auth/signup-with-otp",
        data_template={"phone": "{phone}"},
    ),
    Provider(
        name="Torob OTP",
        url="https://torob.com/v4/user/phone/send-voice-otp/?phone_number=",
        data_template={"phoneNumber": "{phone}"},
    ),
    Provider(
        name="Snappfood OTP",
        url="https://snappfood.ir/v1/auth/otp/send",
        data_template={"phone": "{phone}"},
    ),
]

# To add to your registry:
# from sms_bomber.api.providers import ProviderRegistry
# registry = ProviderRegistry()
# for provider in discovered_providers:
#     registry.add_provider(provider)
