# Auto-fixed providers
# Generated by Provider Auto-Fixer

from sms_bomber.api.providers import Provider

FIXED_PROVIDERS = [
    Provider(
        name="Zigap",
        url="https://api-gateway.zigap.ir/api/v1.9/authenticate/sendotp",
        data_template={'phoneNumber': '+98{phone[1:]}'},
    ),
    Provider(
        name="Mootanroo",
        url="https://api.mootanroo.com/api/v3/auth/send-otp",
        data_template={'phoneNumber': '{phone}'},
    ),
    Provider(
        name="Miare",
        url="https://www.miare.ir/api/otp/driver/request/",
        data_template={'phone': '{phone}'},
    ),
    Provider(
        name="Ostadkr",
        url="https://api.ostadkr.com/login",
        data_template={'mobile': '{phone}'},
    ),
    Provider(
        name="Cafebazaar",
        url="https://api.cafebazaar.ir/rest-v1/process/GetOtpTokenRequest",
        data_template={'phone': '{phone}'},
    ),
]

# Custom headers for these providers (use in client)
PROVIDER_HEADERS = {
    "Zigap": {'Content-Type': 'application/json', 'Accept': 'application/json, text/plain, */*', 'Accept-Language': 'fa-IR,fa;q=0.9,en;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36', 'Sec-Fetch-Dest': 'empty', 'Sec-Fetch-Mode': 'cors', 'Sec-Fetch-Site': 'same-origin'},
    "Mootanroo": {'Content-Type': 'application/json', 'Accept': 'application/json, text/plain, */*', 'Accept-Language': 'fa-IR,fa;q=0.9,en;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36', 'Sec-Fetch-Dest': 'empty', 'Sec-Fetch-Mode': 'cors', 'Sec-Fetch-Site': 'same-origin'},
    "Miare": {'Content-Type': 'application/json', 'Accept': 'application/json, text/plain, */*', 'Accept-Language': 'fa-IR,fa;q=0.9,en;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36', 'Sec-Fetch-Dest': 'empty', 'Sec-Fetch-Mode': 'cors', 'Sec-Fetch-Site': 'same-origin'},
    "Ostadkr": {'Content-Type': 'application/json', 'Accept': 'application/json, text/plain, */*', 'Accept-Language': 'fa-IR,fa;q=0.9,en;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36', 'Sec-Fetch-Dest': 'empty', 'Sec-Fetch-Mode': 'cors', 'Sec-Fetch-Site': 'same-origin'},
    "Cafebazaar": {'Content-Type': 'application/json', 'Accept': 'application/json, text/plain, */*', 'Accept-Language': 'fa-IR,fa;q=0.9,en;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36', 'Sec-Fetch-Dest': 'empty', 'Sec-Fetch-Mode': 'cors', 'Sec-Fetch-Site': 'same-origin'},
}
